name: Test

on:
  pull_request:
    branches: ['main', 'develop']
  push:
    branches: ['main', 'develop']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.13.0']
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install libraries
        run: yarn install
      - name: Run test
        run: yarn test
      - name: Run test e2e
        run: yarn test:e2e
      - name: Run test coverage
        run: yarn test:cov
